In [11]:
import numpy as np
arr = np.arange(1,21)
reshape_array = arr.reshape(2,10)
reshape_array
# array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [12]:
reshape_array.ndim

2

In [13]:
reshape_array.shape

(2, 10)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
# converting 1d array into 3d array
arr3d = arr.reshape(2,2,5)
arr3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [27]:
# [ 
#        [[ 1,  2,  3,  4,  5],
#         [ 6,  7,  8,  9, 10]],

#        [[11, 12, 13, 14, 15],
#         [16, 17, 18, 19, 20]]
# ]

In [30]:
new_arr = np.arange(1,22)
new_arr.reshape(3,1,7)

array([[[ 1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19, 20, 21]]])

# Indexing & Slicing

In [34]:
reshape_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [35]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[1, 1:4]

array([7, 8, 9])

In [38]:
reshape_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [45]:
# array_name [s_row:e_row,s_col:e_col]
reshape_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [48]:
# arr3d[s_layer:e_layer , s_row:e_row, s_col:e_col + 1]
arr3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

## Slicing Syntax

In [49]:
# arr1d[s_value : e_value + 1]
# arr2d[s_row : e_row + 1,s_col:e_col + 1]
# arr3d[s_layer : e_layer + 1, s_row : e_row + 1,s_col:e_col + 1]